### ISSUE TITLE
Требования яндекса не выполнены

### ISSUE THREAD

**Issue by mr-tron** [delvin-fil/Yandex-translator-GUI#3]
https://tech.yandex.com/translate/doc/dg/concepts/design-requirements-docpage/

**Comment by delvin-fil** [comment]
Сейчас исправим.

**Comment by delvin-fil** [comment]
Зделано.
![](https://habrastorage.org/webt/cc/e-/th/cce-th75npthof6uy7mzsjkgute.png)
